### ISSUE TITLE
Troubles with Ecto.Sandbox

### ISSUE THREAD

**Issue by asiniy** [thoughtbot/ex_machina#144]
Hello!

Unfortunately, I can't work with `Ecto 2.0` & `ex_machina 1.0.1` properly. The reason is with sandbox, its can't connect to the database. Let me show you a simple case:

``` elixir
~/projects/myreelty-backend$ cat test/models/inappropriate_test.exs 
defmodule MyReelty.InappropriateTest do
  use MyReelty.ModelCase

  alias MyReelty.Inappropriate
  alias MyReelty.Factory

  @informer Factory.insert(:user) # line 7
  @review   Factory.insert(:review)

  @valid_attrs %{
    informer_id:  @informer.id,
    review_id:    @review.id,
    reason:       "Porn",
    comment:      "Starting on 2:10"
  }

  test "changeset with valid attributes" do
    changeset = Inappropriate.changeset(%Inappropriate{}, @valid_attrs)
    assert changeset.valid?
  end
end
```

I'm running the test suite:

``` elixir
$ mix test test/models/inappropriate_test.exs 
==> erlware_commons
Error evaluating rebar config script ./rebar.config.script:16: evaluation failed with reason error:{badmatch,undefined} and stacktrace [{erl_eval,expr,3,[]}]
Any dependency defined in the script won't be available unless you add them to your Mix project
==> my_reelty
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.336.0>.

When using ownership, you must manage connections in one
of the three ways:

  * By explicitly checking out a connection
  * By explicitly allowing a spawned process
  * By running the pool in shared mode

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

    (db_connection) lib/db_connection.ex:722: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:623: DBConnection.run/3
    (db_connection) lib/db_connection.ex:671: DBConnection.transaction/3
    (ecto) lib/ecto/repo/schema.ex:118: Ecto.Repo.Schema.insert!/4
    test/models/inappropriate_test.exs:7: (module)
```

As you can see, it's failing on line 7 (you can take a look above, it's when Factory is starting to insert a record to the database).

Let me show you the context of another files:

``` elixir
$ cat test/test/helper.exs
{:ok, _} = Application.ensure_all_started(:ex_machina)

ExUnit.start

Ecto.Adapters.SQL.Sandbox.mode(MyReelty.Repo, :manual)
```

``` elixir
$ cat test/support/model_case.ex 
defmodule MyReelty.ModelCase do
  @moduledoc """
  This module defines the test case to be used by
  model tests.

  You may define functions here to be used as helpers in
  your model tests. See `errors_on/2`'s definition as reference.

  Finally, if the test case interacts with the database,
  it cannot be async. For this reason, every test runs
  inside a transaction which is reset at the beginning
  of the test unless the test case is marked as async.
  """

  use ExUnit.CaseTemplate

  using do
    quote do
      alias MyReelty.Repo

      import Ecto
      import Ecto.Changeset
      import Ecto.Query, only: [from: 1, from: 2]
      import MyReelty.ModelCase

      import MyReelty.MapKeysTypeConversion

      use ExSpec, async: true
    end
  end

  setup tags do
    :ok = Ecto.Adapters.SQL.Sandbox.checkout(MyReelty.Repo)

    unless tags[:async] do
      Ecto.Adapters.SQL.Sandbox.mode(MyReelty.Repo, {:shared, self()})
    end

    :ok
  end

  @doc """
  Helper for returning list of errors in model when passed certain data.

  ## Examples

  Given a User model that lists `:name` as a required field and validates
  `:password` to be safe, it would return:

      iex> errors_on(%User{}, %{password: "password"})
      [password: "is unsafe", name: "is blank"]

  You could then write your assertion like:

      assert {:password, "is unsafe"} in errors_on(%User{}, %{password: "password"})

  You can also create the changeset manually and retrieve the errors
  field directly:

      iex> changeset = User.changeset(%User{}, password: "password")
      iex> {:password, "is unsafe"} in changeset.errors
      true
  """
  def errors_on(model, data) do
    model.__struct__.changeset(model, data).errors
  end
end
```

``` elixir
$ cat test/support/factory.ex
defmodule MyReelty.Factory do
  use ExMachina.Ecto, repo: MyReelty.Repo

  def user_factory do
    %MyReelty.User{
      email:             sequence(:email, &"info-#{&1}@myreelty.com"),
      password:          password,
      name:              "Ori Ayonmike",
      crypted_password:  Comeonin.Bcrypt.hashpwsalt(password)
    }
  end

  def admin_factory do
    build(:user) |> Map.merge(%{ admin: true })
  end
end
```

How can I make it works?

**Comment by paulcsmith** [comment]
@asiniy I believe this is not an issue with ExMachina, but instead an issue with the way Ecto 2.0 works. In Ecto 2.0 you need to checkout a connection. Since `@informer Factory.insert(:user) # line 7` is an attribute, it happens at compile time, and no connection is checked out. I believe you can do this by instead making private functions, instead of using `@`

Something like this:

```elixir
  @valid_attrs %{
    informer_id:  informer.id,
    review_id:    review.id,
    reason:       "Porn",
    comment:      "Starting on 2:10"
  }

  defp informer do
    insert(:user)
  end
  
  defp review do
     insert(:review)
  end
```

Though even that may not work since the test db will be cleared between runs. So you may also have to make `@valid_attrs` into a private function as well.

Another option is to use `params_with_assocs(:inappropriate)` which will insert belongs_to associations and return the params. This is nice because then you don't need to duplicate params in the factory and in the test. LMK if this helps or if I need to provide more clarification

**Comment by paulcsmith** [comment]
BTW I'm going to close this for now, but please comment if you need further help

**Comment by asiniy** [comment]
@paulcsmith thanks it works

**Comment by paulcsmith** [comment]
@asiniy great! I'm glad it did
