### ISSUE TITLE
ex_machina insert raises UndefinedFunctionError error

### ISSUE THREAD

**Issue by Chatatata** [thoughtbot/ex_machina#160]
I have two Ecto models:

```
defmodule MyApp.User do
  use MyApp.Web, :model

  schema "users" do
    field :username, :string
    field :email, :string
    field :password_digest, :string
  end
end

defmodule MyApp.AuthAttempt do
  use MyApp.Web, :model

  schema "auth_attempts" do
    field :ip_addr, :string
    field :username, :string
    field :success, :boolean, default: false
  end
end
```

The following raises error:
```
user = Factory.insert(:user)
auth_attempt = Factory.insert(:auth_attempt, username: user.username)

** (UndefinedFunctionError) function MyApp.AuthAttempt.fetch/2 is undefined (MyApp.AuthAttempt does not implement the Access behaviour)
     stacktrace:
       (my_app) MyApp.AuthAttempt.fetch(%MyApp.AuthAttempt{__meta__: #Ecto.Schema.Metadata<:loaded, "auth_attempts">, id: 48, inserted_at: #Ecto.DateTime<2016-09-08 22:35:11>, ip_addr: "0.0.0.0", success: true, updated_at: #Ecto.DateTime<2016-09-08 22:35:11>, username: "user1"}, "ip_addr")
       (elixir) lib/access.ex:148: Access.fetch/2
       (elixir) lib/access.ex:179: Access.get/3
       (my_app) web/views/auth_attempt_view.ex:16: MyApp.AuthAttemptView.render/2
       (my_app) web/views/auth_attempt_view.ex:12: MyApp.AuthAttemptView.render/2
       (phoenix) lib/phoenix/view.ex:335: Phoenix.View.render_to_iodata/3
       (phoenix) lib/phoenix/controller.ex:642: Phoenix.Controller.do_render/4
       (my_app) web/controllers/auth_attempt_controller.ex:1: MyApp.AuthAttemptController.action/2
       (my_app) web/controllers/auth_attempt_controller.ex:1: MyApp.AuthAttemptController.phoenix_controller_pipeline/2
       (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.instrument/4
       (my_app) lib/phoenix/router.ex:261: MyApp.Router.dispatch/2
       (my_app) web/router.ex:1: MyApp.Router.do_call/2
       (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.phoenix_pipeline/1
       (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/auth_attempt_controller_test.exs:20: (test)
```

I could not even figure out what the problem is. Do you have an idea?

Thank you.

**Comment by paulcsmith** [comment]
@Chatatata I would recommend posting this in the Elixir Slack room or on https://elixirforum.com next time for a quicker response.

It looks to me like this is not an ExMachina error and is a problem in your AuthAttemptView. The stack trace has: `(my_app) web/views/auth_attempt_view.ex:16: MyApp.AuthAttemptView.render/2` So I'd take a look there. I'm going to go ahead and close this. If you need more help, feel free to comment here or try Slack or the forums
