### ISSUE TITLE
Data type in factory

### ISSUE THREAD

**Issue by romariolopez** [thoughtbot/ex_machina#163]
How to cast other params?
```
def person_factory do
     %Person {
       name: "Romario",
       last_name: "Lopez Castillo",
       gender: :male,
       birthdate: Ecto.Date.cast("1994-02-19"), #tried with only the string "1994-02-19"
       contact_phone: "991247"
    }
   end
```

```
 ** (Ecto.ChangeError) value `{:ok, #Ecto.Date<1994-02-19>}` for `Person.birthdate` in `insert` does not match type Ecto.Date
     stacktrace:
       (ecto) lib/ecto/repo/schema.ex:629: Ecto.Repo.Schema.dump_field!/6
       (ecto) lib/ecto/repo/schema.ex:638: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
       (stdlib) lists.erl:1263: :lists.foldl/3
       (ecto) lib/ecto/repo/schema.ex:636: Ecto.Repo.Schema.dump_fields!/5
       (ecto) lib/ecto/repo/schema.ex:585: Ecto.Repo.Schema.dump_changes!/6
       (ecto) lib/ecto/repo/schema.ex:190: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/association.ex:765: Ecto.Association.BelongsTo.on_repo_change/4
       (ecto) lib/ecto/association.ex:214: Ecto.Association.on_repo_change/6
       (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/association.ex:194: Ecto.Association.on_repo_change/3
       (ecto) lib/ecto/repo/schema.ex:521: Ecto.Repo.Schema.process_parents/3
       (ecto) lib/ecto/repo/schema.ex:183: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:614: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:508: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1063: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:987: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:667: DBConnection.transaction/3
       (ecto) lib/ecto/repo/schema.ex:124: Ecto.Repo.Schema.insert!/4
       test/controllers/api/v1/medical_information_controller_test.exs:47: (test)
```

If i use only the string part of date `birthdate: "1994-02-19",`, it shows this:
```
** (Ecto.ChangeError) value `"1994-02-19"` for `Person.birthdate` in `insert` does not match type Ecto.Date
     stacktrace:
       (ecto) lib/ecto/repo/schema.ex:629: Ecto.Repo.Schema.dump_field!/6
       (ecto) lib/ecto/repo/schema.ex:638: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
       (stdlib) lists.erl:1263: :lists.foldl/3
       (ecto) lib/ecto/repo/schema.ex:636: Ecto.Repo.Schema.dump_fields!/5
       (ecto) lib/ecto/repo/schema.ex:585: Ecto.Repo.Schema.dump_changes!/6
       (ecto) lib/ecto/repo/schema.ex:190: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/association.ex:765: Ecto.Association.BelongsTo.on_repo_change/4
       (ecto) lib/ecto/association.ex:214: Ecto.Association.on_repo_change/6
       (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/association.ex:194: Ecto.Association.on_repo_change/3
       (ecto) lib/ecto/repo/schema.ex:521: Ecto.Repo.Schema.process_parents/3
       (ecto) lib/ecto/repo/schema.ex:183: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:614: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:508: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1063: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:987: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:667: DBConnection.transaction/3
       (ecto) lib/ecto/repo/schema.ex:124: Ecto.Repo.Schema.insert!/4
       test/controllers/api/v1/medical_information_controller_test.exs:47: (test)
```

**Comment by paulcsmith** [comment]
The problem is that `Ecto.Date.cast` returns a tuple `{:ok, the_date}` You need to use `Ecto.Date.cast!` (note the `!`) so that it returns the Ecto.Date struct instead of the a tuple
