### ISSUE TITLE
Testing using UUID primary keys

### ISSUE THREAD

**Issue by madshargreave** [thoughtbot/ex_machina#216]
Hi

I use UUID for all my models

```
@primary_key {:id, :binary_id, autogenerate: true}
@foreign_key_type :binary_id
```

And I get the following error when trying to insert any a record

```
    ** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire): invalid byte sequence for encoding "UTF8": 0xbc
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:570: Ecto.Adapters.SQL.struct/7
       (ecto) lib/ecto/repo/schema.ex:459: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:198: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:676: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:615: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
       (ecto) lib/ecto/repo/schema.ex:128: Ecto.Repo.Schema.insert!/4
       test/controllers/dashboard/v1/conversation_receipts_controller_test.exs:7: ResendWeb.Dashboard.V1.ReceiptControllerTest.__ex_unit_setup_1/1
       test/controllers/dashboard/v1/conversation_receipts_controller_test.exs:1: ResendWeb.Dashboard.V1.ReceiptControllerTest.__ex_unit__/2
```

Are UUID's not supported?

**Comment by anthonator** [comment]
I don't have any issues using UUID's with ExMachina.

**Comment by paulcsmith** [comment]
@madshargreave ExMachina supports UUID's. That looks like there may be a different issue going on here. I would try posting on Ecto or on the Elixir forums/Slack so see if someone can help you there that has more experience with these types of errors. Sorry. I wish I could help more!
