### ISSUE TITLE
Bug: possible bug when using the sequence method

### ISSUE THREAD

**Issue by digitalcake** [thoughtbot/ex_machina#218]
I think I possibly found a bug when using the sequence method. 

Factory.ex
```elixir
  def post_factory do
    %Post{
      title: sequence("Article Title"),
      slug: sequence("article-title"),
      excerpt: "some excerpt",
      body: "some body",
      published_at: Ecto.Date.utc,
      draft: false,
      category: build(:category)
    }
  end
```

Pry:
```
pry(1)> insert(:post)
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * unique: posts_slug_index

If you would like to convert this constraint into an error, please
call unique_constraint/3 in your changeset and define the proper
constraint name. The changeset has not defined any constraint.

             (ecto) lib/ecto/repo/schema.ex:493: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
           (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
             (ecto) lib/ecto/repo/schema.ex:479: Ecto.Repo.Schema.constraints_to_errors/3
             (ecto) lib/ecto/repo/schema.ex:213: anonymous fn/13 in Ecto.Repo.Schema.do_insert/4
             (ecto) lib/ecto/repo/schema.ex:684: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
             (ecto) lib/ecto/adapters/sql.ex:620: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
             (ecto) lib/ecto/repo/schema.ex:131: Ecto.Repo.Schema.insert!/4
           (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
              (iex) lib/iex/evaluator.ex:182: IEx.Evaluator.handle_eval/6
              (iex) lib/iex/evaluator.ex:175: IEx.Evaluator.do_eval/4
              (iex) lib/iex/evaluator.ex:155: IEx.Evaluator.eval/4
              (iex) lib/iex/evaluator.ex:61: IEx.Evaluator.loop/3
              (iex) lib/iex/evaluator.ex:21: IEx.Evaluator.init/4
              (iex) lib/iex.ex:471: IEx.pry/3
                    test/controllers/post_controller_test.exs:67: Digitalcakes.PostControllerTest."test shows chosen resource"/1
```

But as you can see I am calling unique_constraint in my changeset. 
```elixir
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :slug, :excerpt, :body, :published_at, :draft, :category_id])
    |> validate_required([:title, :slug, :excerpt, :body, :published_at, :draft])
    |> validate_format(:slug, ~r/^[a-z0-9](-?[a-z0-9]+)*$/)
    |> unique_constraint(:slug)
  end
```

Thoughts?

**Comment by digitalcake** [comment]
looks like for some reason my db was not cleaning up and there was records in there that caused this.
