### ISSUE TITLE
Upgraded from 2.0.0 to 2.1.0 and now getting errors related to timestamps()

### ISSUE THREAD

**Issue by digitalcake** [thoughtbot/ex_machina#269]
Getting a log of failing tests now after I upgraded and it looks to be related to timestamps

```
❯ mix test test/myapp/accounts/accounts_test.exs:25
Including tags: [line: "25"]
Excluding tags: [:test]



  1) test users get_user!/1 returns the user with given id (MyApp.AccountsTest)
     test/my_app/accounts/accounts_test.exs:25
     ** (Postgrex.Error) ERROR 23502 (not_null_violation): null value in column "inserted_at" violates not-null constraint

         table: users
         column: inserted_at

     Failing row contains (18185, email-1@example.com, null, null, null, null, null, null, null, null, null, t, null, null, 23242, null, 0, null, {}).
     code: user = user_fixture()
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.struct/8
       (ecto) lib/ecto/repo/schema.ex:547: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:213: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:774: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
       (ecto) lib/ecto/repo/schema.ex:125: Ecto.Repo.Schema.insert!/4
       test/my_app/accounts/accounts_test.exs:15: MyApp.AccountsTest.user_fixture/0
       test/my_app/accounts/accounts_test.exs:26: (test)
```

Factory:
```
defmodule MyApp.Factory do
  use ExMachina.Ecto, repo: MyApp.Repo
 ...

  def user_factory do
    %MyApp.Accounts.User{
      email: sequence(:email, &"email-#{&1}@example.com"),
      active: true,
      failed_attempts: 0,
      locked_at: nil,
      department: build(:department)
    }
  end
...

end
```

Test:

```

    def user_fixture() do
      insert(:user) # fails here  test/my_app/accounts/accounts_test.exs:15: MyApp.AccountsTest.user_fixture/0
      |> MyApp.Repo.preload(:department)
      |> MyApp.Repo.preload(:programs)
    end

    test "get_user!/1 returns the user with given id" do
      user = user_fixture()
      assert Accounts.get_user!(user.id) == user
    end
```

**Comment by digitalcake** [comment]
Found the issue is related to trying to change the default way timestamps are stored. 

Ie

```

  @timestamps_opts [
    type: Timex.Ecto.TimestampWithTimezone,
    autogenerate: {Timex.Ecto.TimestampWithTimezone, :autogenerate}
  ]
```
