### ISSUE TITLE
Error on "nested" builds

### ISSUE THREAD

**Issue by bbtdev** [thoughtbot/ex_machina#293]
Hello,
New to Elixir, Ecto, ExMachina, so maybe it is not possible to do this, but this shoud've worked?:

Let's say:
```
%Restaurant{} has many %Discount{}
%Discount{} has many %PromoCode{}
```
Factories:
```
def restaurant_factory do
  %Restaurant{ 
     discounts: [ 
        build(:discount)
     ] 
   }
end 

def discount_factory do
   %Discount{
        promo_codes: [
             build(:promo_code)
        ]
    }
 end 

def promo_code_factory do
     %PromoCode{}
end
```

The test on line 42:
```
test "test load discount by promo code" do
    r = insert(:restaurant)
end 
```
When I run:
`iex -S mix test --trace test/services/load_discounts/service_test.exs:42`

I get:
```
test load discount by promo code (Restaurants.Domain.LoadDiscountsServiceTest)
     test/services/load_discounts/service_test.exs:42
     ** (ArgumentError) expected changeset data to be a Elixir.Restaurants.Domain.Models.Discount struct, got: %Res
taurants.Domain.Models.PromoCode{__meta__: #Ecto.Schema.Metadata<:built, "promo_codes">, code: "XXYY6Z", created_at
: nil, discounts: #Ecto.Association.NotLoaded<association :discounts is not loaded>, discounts_id: nil, id: nil, up
dated_at: nil, use_limit: 3}
     stacktrace:
       (ecto) lib/ecto/changeset/relation.ex:190: Ecto.Changeset.Relation.assert_changeset_struct!/2
       (ecto) lib/ecto/changeset/relation.ex:148: Ecto.Changeset.Relation.do_change/4
       (ecto) lib/ecto/changeset/relation.ex:312: Ecto.Changeset.Relation.map_changes/8
       (ecto) lib/ecto/repo/schema.ex:597: anonymous fn/4 in Ecto.Repo.Schema.surface_changes/3
       (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/repo/schema.ex:584: Ecto.Repo.Schema.surface_changes/3
       (ecto) lib/ecto/repo/schema.ex:189: Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/association.ex:556: Ecto.Association.Has.on_repo_change/4
       (ecto) lib/ecto/association.ex:338: anonymous fn/7 in Ecto.Association.on_repo_change/6
       (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/association.ex:335: Ecto.Association.on_repo_change/6
       (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/association.ex:301: Ecto.Association.on_repo_change/3
       (ecto) lib/ecto/repo/schema.ex:708: Ecto.Repo.Schema.process_children/4
       (ecto) lib/ecto/repo/schema.ex:774: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
       (ecto) lib/ecto/repo/schema.ex:125: Ecto.Repo.Schema.insert!/4
```

**Comment by bbtdev** [comment]
Noob mistake, my associations were wrong! So sorry!

**Comment by paulcsmith** [comment]
No problem! Glad you were able to fix it!
