### ISSUE TITLE
Inserted data breaks manual test

### ISSUE THREAD

**Issue by Mdsp9070** [thoughtbot/ex_machina#409]
I build a user factory and used on `setup` for session test (phoenix API), but the third test seems to use ex_machina inserted user and not which I pass to the function. What can be happening?

test suite:
```elixir
defmodule BankWeb.SessionTest do
  use BankWeb.ConnCase, async: true

  import Bank.Factory

  @user_not_exists %{
    email: "mario@gmail.com.br",
    password: "12345678910",
    password_confirmation: "12345678910"
  }

  describe "login" do
    setup %{conn: conn} do
      user = insert(:user, confirmed?: true)

      %{conn: conn, user: user}
    end

    test "login with a valid data", %{conn: conn, user: user} do
      conn =
        conn
        |> post(Routes.session_path(conn, :create), %{
          email: user.email,
          password: "12345678910",
          password_confirmation: "12345678910"
        })
        |> doc(
          "Returns token for this api",
          resp_trans: %{token: "veryLongToken"},
          params_descr: [email: "Account email", password: "Account password"],
          on_nil: [email: :error, password: :error, password_confirmation: :error]
        )

      %{"message" => message} = json_response(conn, 200)
      assert message == "login_success"
    end

    test "login with a wrong password", %{conn: conn, user: user} do
      conn =
        conn
        |> post(Routes.session_path(conn, :create), %{
          email: user.email,
          password: "979797979",
          password_confirmation: "979797979"
        })

      %{"message" => message} = json_response(conn, 401)
      assert message == "invalid_password"
    end

    test "login with an invalid user", %{conn: conn} do
      conn =
        conn
        |> post(Routes.session_path(conn, :create), @user_not_exists)

      %{"message" => message} = json_response(conn, 401)
      assert message == "email_not_registered"
    end
  end
end
```

tests output:
```sh
REQUEST PARAM: %{
  "email" => "matheus0@outlook.com",
  "password" => "979797979",
  "password_confirmation" => "979797979"
}
FOUND USER: %Bank.Accounts.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  balance: 0,
  cnpj: nil,
  confirmation: #Ecto.Association.NotLoaded<association :confirmation is not loaded>,
  confirmed?: true,
  cpf: "123.456.789-00",
  email: "matheus0@outlook.com",
  first_name: "matheus",
  id: "dd0364f9-191b-4227-af77-3b783ce7e554",
  inserted_at: ~N[2021-01-05 05:59:58],
  last_name: "pessanha",
  mobile: "(22)12345-6780",
  pass_recovery: #Ecto.Association.NotLoaded<association :pass_recovery is not loaded>,
  password: nil,
  password_confirmation: nil,
  password_hash: "$argon2id$v=19$m=131072,t=8,p=4$eazccRzx+8zVgvsPDp7xJQ$AgQ1hFHbCf5+GiheRMdx43fFIS8SWDw/KEdPzsp+qJY",
  updated_at: ~N[2021-01-05 05:59:58]
}
.REQUEST PARAM: %{
  "email" => "matheus1@outlook.com",
  "password" => "12345678910",
  "password_confirmation" => "12345678910"
}
FOUND USER: %Bank.Accounts.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  balance: 0,
  cnpj: nil,
  confirmation: #Ecto.Association.NotLoaded<association :confirmation is not loaded>,
  confirmed?: true,
  cpf: "123.456.789-01",
  email: "matheus1@outlook.com",
  first_name: "matheus",
  id: "c708b3bc-e7da-49cb-b54c-e3874d7cf382",
  inserted_at: ~N[2021-01-05 05:59:59],
  last_name: "pessanha",
  mobile: "(22)12345-6781",
  pass_recovery: #Ecto.Association.NotLoaded<association :pass_recovery is not loaded>,
  password: nil,
  password_confirmation: nil,
  password_hash: "$argon2id$v=19$m=131072,t=8,p=4$r5MxuFxx43KpIVTEkahJcg$ZKzIwZ4sf3E7I7bbkxB2ShUTffWWKNgaXdscPt8b8g0",
  updated_at: ~N[2021-01-05 05:59:59]
}
.REQUEST PARAM: %{
  "email" => "mario@gmail.com.br",
  "password" => "12345678910",
  "password_confirmation" => "12345678910"
}
FOUND USER: %Bank.Accounts.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  balance: 0,
  cnpj: nil,
  confirmation: #Ecto.Association.NotLoaded<association :confirmation is not loaded>,
  confirmed?: true,
  cpf: "123.456.789-02",
  email: "matheus2@outlook.com",
  first_name: "matheus",
  id: "4240212e-26a7-48fd-8b9a-5f9c21db137f",
  inserted_at: ~N[2021-01-05 06:00:01],
  last_name: "pessanha",
  mobile: "(22)12345-6782",
  pass_recovery: #Ecto.Association.NotLoaded<association :pass_recovery is not loaded>,
  password: nil,
  password_confirmation: nil,
  password_hash: "$argon2id$v=19$m=131072,t=8,p=4$UTMcTmJfuN00f28T2IL0aw$mjpcvcsq0OyLJPtTQpskd5hip1N7JUDTXEhFBmqIOnw",
  updated_at: ~N[2021-01-05 06:00:01]
}


  1) test login login with an invalid user (BankWeb.SessionTest)
     test/bank_web/controllers/session_controller_test.exs:51
     ** (RuntimeError) expected response with status 401, got: 200, with body:
     "{\"data\":\"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJiYW5rIiwiZXhwIjoxNjEyMjQ1NjAxLCJpYXQiOjE2MDk4MjY0MDEsImlzcyI6ImJhbmsiLCJqdGkiOiJmNWNhM2Y0Yy0zMjI2LTQxOGUtYTBjOC02ZDFmYzAyNDA0MzgiLCJuYmYiOjE2MDk4MjY0MDAsInN1YiI6IjQyNDAyMTJlLTI2YTctNDhmZC04YjlhLTVmOWMyMWRiMTM3ZiIsInR5cCI6ImFjY2VzcyJ9.YwlL5ykCLL-5jufIBl7KCt8Jm3YcuqpocKmDoEjoygSu9VzhXXyrCKA-0LxR8w759TlEGGRZLcqIqktPOceBXQ\",\"message\":\"login_success\"}"
     code: %{"message" => message} = json_response(conn, 401)
     stacktrace:
       (phoenix 1.5.7) lib/phoenix/test/conn_test.ex:369: Phoenix.ConnTest.response/2
       (phoenix 1.5.7) lib/phoenix/test/conn_test.ex:415: Phoenix.ConnTest.json_response/2
       test/bank_web/controllers/session_controller_test.exs:56: (test)

.......

Finished in 13.2 seconds
12 tests, 1 failure

Randomized with seed 907948
```

**Comment by germsvel** [comment]
Hi @Mdsp9070, it's tough for me to know what might be wrong given the code you shared. It seems to me like this might not be ExMachina related. I see you're inserting a user in the `setup` and I see that you pass different credentials for the third test, but I don't know what your code is doing when the request is made (in the SessionController). 

Could you provide a sample app that reproduces the error? I think if I could see that I might be able to help more.

**Comment by Mdsp9070** [comment]
Hi! Thanks for replying! So, for now I can't provide a sample app (I'm going to home). But for now, here's the controller code:
```elixir
defmodule BankWeb.SessionController do
  @moduledoc """
  Manages session creation and removal
  """
  use BankWeb, :controller

  alias BankWeb.Auth

  action_fallback BankWeb.FallbackController

  @accepts [:email, :password, :password_confirmation]
  @doc "Creates a session if password matches"
  @spec create(Plug.Conn.t(), map()) :: {:ok, map()} | {:error, any()}
  def create(_conn, params) do
    case Auth.login(params) do
      {:ok, data} -> {:ok, %{message: :login_success, data: data}}
      error -> error
    end
  end
end
```

As soons as I arrive to work I'll try to reproduce the error on a sample app.

**Comment by Mdsp9070** [comment]
In fact, the problem was in a macro I was using wrongly! Thanks for the attention!
